## DATA CLEANING SCRIPT

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
df = pd.read_csv("C:/Users/ADMIN/Desktop/PROJECTS/Luxury Housing Sales Analysis Project/Luxury_Housing_Bangalore.csv")

In [4]:
df
#df.head()
#df.tail()
#df.shape
#df.columns
#df.info()
#df.describe()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [5]:
df.columns = df.columns.str.strip().str.replace(" ", "_").str.replace("-", "_")

In [6]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

### HANDLING MISSING VALUES

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [8]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

#### FILLING MISSING FIELDS

In [9]:
num_cols = ['Unit_Size_Sqft','Ticket_Price_Cr','Amenity_Score']
for col in num_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r'[^0-9\.]', '', regex=True)  
        .replace('', None))
    
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [10]:
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20164\4074283006.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20164\4074283006.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20164\4074283006.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [11]:
print(df[num_cols].isnull().sum())

Unit_Size_Sqft     0
Ticket_Price_Cr    0
Amenity_Score      0
dtype: int64

In [12]:
df[num_cols]

        Unit_Size_Sqft  Ticket_Price_Cr  Amenity_Score
0               4025.0        12.750846       5.462863
1               5760.0        16.292152       7.499123
2               7707.0        10.517724       8.669227
3               6192.0         9.396367       5.720246
4               7147.0        15.345392       8.609649
...                ...              ...            ...
100995          8546.0        11.330810       6.221131
100996          3408.0        10.829373       9.783611
100997          4691.0        11.183303       8.383013
100998          7435.0        10.914156       5.756247
100999          3218.0        13.270000       9.989290

[101000 rows x 3 columns]

In [13]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.499123,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [14]:
text_cols = df.select_dtypes(include='object').columns
df[text_cols].isnull().sum()

Property_ID              0
Micro_Market             0
Project_Name             0
Developer_Name           0
Configuration            0
Transaction_Type         0
Buyer_Type               0
Purchase_Quarter         0
Possession_Status        0
Sales_Channel            0
NRI_Buyer                0
Buyer_Comments       18287
dtype: int64

In [15]:
text_cols = ['Buyer_Comments']
for col in text_cols:
    if col in df.columns:
        df[col].fillna('Unknown', inplace=True)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20164\3075501583.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna('Unknown', inplace=True)

In [16]:
text_cols = df.select_dtypes(include='object').columns
df[text_cols].isnull().sum()

Property_ID          0
Micro_Market         0
Project_Name         0
Developer_Name       0
Configuration        0
Transaction_Type     0
Buyer_Type           0
Purchase_Quarter     0
Possession_Status    0
Sales_Channel        0
NRI_Buyer            0
Buyer_Comments       0
dtype: int64

#### NORMALIZATION

In [17]:
df['Developer_Name'].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [18]:
df['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [19]:
df['Developer_Name'] = df['Developer_Name'].astype(str).str.upper()
df['Micro_Market'] = df['Micro_Market'].astype(str).str.upper()
df['Configuration'] = df['Configuration'].astype(str).str.upper()

In [20]:
df['Micro_Market'].unique()

array(['SARJAPUR ROAD', 'INDIRANAGAR', 'BANNERGHATTA ROAD',
       'BELLARY ROAD', 'KORAMANGALA', 'YELAHANKA', 'WHITEFIELD',
       'JP NAGAR', 'RAJAJINAGAR', 'JAYANAGAR', 'DOMLUR', 'MG ROAD',
       'HENNUR ROAD', 'ELECTRONIC CITY', 'HEBBAL', 'KANAKAPURA ROAD'],
      dtype=object)

In [21]:
df['Developer_Name'].unique()

array(['RMZ', 'PURAVANKARA', 'TATA HOUSING', 'EMBASSY', 'SNN RAJ',
       'BRIGADE', 'PRESTIGE', 'TOTAL ENVIRONMENT', 'GODREJ', 'L&T REALTY',
       'SOBHA'], dtype=object)

#### ADD COLUMNS

In [22]:
df['Transaction_Type'].unique()

array(['Primary', 'Secondary'], dtype=object)

In [23]:
df['Price_per_Sqft'] = df['Ticket_Price_Cr'] / df['Unit_Size_Sqft']

df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'], errors = 'coerce')

df['Quarter_Number'] = df['Purchase_Quarter'].dt.quarter

df['Year'] = df['Purchase_Quarter'].dt.year

df['Booking_Flag'] = df['Transaction_Type'].apply(
    lambda x: 1 if str(x).strip() == 'Primary' else 0)

In [24]:
df["Booking_Flag"]

0         1
1         1
2         1
3         1
4         0
         ..
100995    0
100996    1
100997    1
100998    0
100999    1
Name: Booking_Flag, Length: 101000, dtype: int64

In [25]:
df['Year']

0         2025
1         2024
2         2023
3         2024
4         2024
          ...
100995    2024
100996    2024
100997    2023
100998    2024
100999    2023
Name: Year, Length: 101000, dtype: int32

In [26]:
df['Purchase_Quarter']

0        2025-03-31
1        2024-06-30
2        2023-12-31
3        2024-03-31
4        2024-12-31
            ...
100995   2024-12-31
100996   2024-09-30
100997   2023-12-31
100998   2024-06-30
100999   2023-12-31
Name: Purchase_Quarter, Length: 101000, dtype: datetime64[ns]

In [27]:
df['Avg_Traffic_Time_Min']

0          18
1         106
2         113
3         106
4          18
         ...
100995     22
100996     26
100997     44
100998     66
100999     58
Name: Avg_Traffic_Time_Min, Length: 101000, dtype: int64

In [28]:
df['Micro_Market'].unique()

array(['SARJAPUR ROAD', 'INDIRANAGAR', 'BANNERGHATTA ROAD',
       'BELLARY ROAD', 'KORAMANGALA', 'YELAHANKA', 'WHITEFIELD',
       'JP NAGAR', 'RAJAJINAGAR', 'JAYANAGAR', 'DOMLUR', 'MG ROAD',
       'HENNUR ROAD', 'ELECTRONIC CITY', 'HEBBAL', 'KANAKAPURA ROAD'],
      dtype=object)

In [29]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number,Year,Booking_Flag
0,PROP000001,SARJAPUR ROAD,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,Launch,Broker,yes,9.212491,18,Loved the amenities!,0.003168,1,2025,1
1,PROP000002,INDIRANAGAR,Project_1,PURAVANKARA,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,Under construction,NRI Desk,no,7.723898,106,Unknown,0.002828,2,2024,1
2,PROP000003,BANNERGHATTA ROAD,Project_2,TATA HOUSING,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,0.001365,4,2023,1
3,PROP000004,BELLARY ROAD,Project_3,EMBASSY,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Ready to move,Online,yes,6.100929,106,Excellent location!,0.001518,1,2024,1
4,PROP000005,KORAMANGALA,Project_4,SNN RAJ,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,Under construction,Broker,no,5.312510,18,Too far from my office.,0.002147,4,2024,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,EMBASSY,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,...,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.,0.001326,4,2024,0
100996,PROP059810,BELLARY ROAD,Project_309,BRIGADE,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,...,Ready to move,Direct,no,9.851849,26,Agent was not responsive.,0.003178,3,2024,1
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,...,Under construction,Broker,no,9.101604,44,Loved the amenities!,0.002384,4,2023,1
100998,PROP093022,RAJAJINAGAR,Project_21,EMBASSY,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,...,Under construction,Broker,yes,8.588551,66,Excellent location!,0.001468,2,2024,0
100999,PROP023826,WHITEFIELD,Project_325,L&T REALTY,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,...,Under construction,Direct,yes,9.917647,58,Loved the amenities!,0.004124,4,2023,1

## CONNECT TO POSTGRESQL

In [30]:
username = "postgres"
password = "root"
host = "localhost"
port = "5432"
database = "LHSA_DATA"

connection_url = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"

engine = create_engine(connection_url)

In [31]:
df.columns = [c.strip().lower().replace(' ', '_') for c in df.columns]

In [32]:
df.to_sql('luxury_housing_cleaned', con=engine, if_exists='append', index=False)

1000

In [33]:
test = pd.read_sql("SELECT COUNT(*) AS total_rows FROM luxury_housing_cleaned;", con=engine)
print(test)

   total_rows
0      202000

In [34]:
query = """
SELECT 
    column_name, 
    data_type
FROM information_schema.columns
WHERE table_name = 'luxury_housing_cleaned'
ORDER BY ordinal_position;
"""

columns_df = pd.read_sql(query, con=engine)
print("Table structure in PostgreSQL:\n")
print(columns_df)

Table structure in PostgreSQL:

             column_name         data_type
0            property_id              text
1           micro_market              text
2           project_name              text
3         developer_name              text
4         unit_size_sqft  double precision
5          configuration              text
6        ticket_price_cr  double precision
7       transaction_type              text
8             buyer_type              text
9       purchase_quarter              date
10    connectivity_score  double precision
11         amenity_score  double precision
12     possession_status              text
13         sales_channel              text
14             nri_buyer           boolean
15  locality_infra_score  double precision
16  avg_traffic_time_min           integer
17        buyer_comments              text
18        price_per_sqft  double precision
19        quarter_number           integer
20                  year           integer
21          booking_flag           integer

In [35]:
print("DataFrame columns:")
print(df.columns.tolist())

DataFrame columns:
['property_id', 'micro_market', 'project_name', 'developer_name', 'unit_size_sqft', 'configuration', 'ticket_price_cr', 'transaction_type', 'buyer_type', 'purchase_quarter', 'connectivity_score', 'amenity_score', 'possession_status', 'sales_channel', 'nri_buyer', 'locality_infra_score', 'avg_traffic_time_min', 'buyer_comments', 'price_per_sqft', 'quarter_number', 'year', 'booking_flag']

In [36]:
df

,property_id,micro_market,project_name,developer_name,unit_size_sqft,configuration,ticket_price_cr,transaction_type,buyer_type,purchase_quarter,...,possession_status,sales_channel,nri_buyer,locality_infra_score,avg_traffic_time_min,buyer_comments,price_per_sqft,quarter_number,year,booking_flag
0,PROP000001,SARJAPUR ROAD,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,Launch,Broker,yes,9.212491,18,Loved the amenities!,0.003168,1,2025,1
1,PROP000002,INDIRANAGAR,Project_1,PURAVANKARA,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,Under construction,NRI Desk,no,7.723898,106,Unknown,0.002828,2,2024,1
2,PROP000003,BANNERGHATTA ROAD,Project_2,TATA HOUSING,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,0.001365,4,2023,1
3,PROP000004,BELLARY ROAD,Project_3,EMBASSY,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Ready to move,Online,yes,6.100929,106,Excellent location!,0.001518,1,2024,1
4,PROP000005,KORAMANGALA,Project_4,SNN RAJ,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,Under construction,Broker,no,5.312510,18,Too far from my office.,0.002147,4,2024,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,EMBASSY,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,...,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.,0.001326,4,2024,0
100996,PROP059810,BELLARY ROAD,Project_309,BRIGADE,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,...,Ready to move,Direct,no,9.851849,26,Agent was not responsive.,0.003178,3,2024,1
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,...,Under construction,Broker,no,9.101604,44,Loved the amenities!,0.002384,4,2023,1
100998,PROP093022,RAJAJINAGAR,Project_21,EMBASSY,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,...,Under construction,Broker,yes,8.588551,66,Excellent location!,0.001468,2,2024,0
100999,PROP023826,WHITEFIELD,Project_325,L&T REALTY,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,...,Under construction,Direct,yes,9.917647,58,Loved the amenities!,0.004124,4,2023,1